// cad++ — hand-authored stroke glyphs for the small set of non-ASCII
// codepoints AutoCAD drawings reach for outside the Hershey ASCII
// range. SPDX-License-Identifier: GPL-3.0-or-later
//
// `hershey_data.hpp` is generated by `tools/hershey/extract.mjs` from
// the upstream `hersheytext` JSON and only covers ASCII 0x21..0x7F.
// Regenerating that header overwrites whatever is in it, so geometric
// symbols (degree, plus-minus, diameter) live in this side-car file
// — the runtime checks here when the ASCII lookup falls through, and
// only falls back to the tofu placeholder when this side-car misses
// too.
//
// Coordinate system + sentinel encoding mirror `hershey_data.hpp`:
//   - units = Hershey ints, cap-top at y=1, baseline at y=22,
//     cap_height = 21.
//   - pen-up sentinel = (-128, -128) pair.
//   - advance is the raw `o`; the runtime multiplies by
//     `detail::k_advance_factor` for the final canvas-pixel pitch.

#pragma once

namespace cadpp::hershey::detail {

// ---------- degree sign U+00B0 (°) ----------
//
// Small circle in the upper third of the cap region. Approximated by
// an 8-point octagon (3-unit radius around (4, 4)) so the inkprint
// reads as a circle at the small sizes most DWGs use for tolerance /
// angle markers. Same y-range as a digit superscript would occupy.
inline constexpr std::int8_t k_degree_strokes[] = {
    7, 4,  6, 2,  4, 1,  2, 2,  1, 4,  2, 6,  4, 7,  6, 6,  7, 4,
};

// ---------- plus-minus sign U+00B1 (±) ----------
//
// A small plus on top of a dash, sized to match a digit's visible
// region. The plus's cross-bar (y=9) and vertical bar (x=5) put the
// centroid at the cap region's mid-line; the minus sits below at
// baseline-2 so the pair reads as one composed glyph.
inline constexpr std::int8_t k_plusminus_strokes[] = {
    5, 4,    5, 14,
    -128, -128,
    1, 9,    9, 9,
    -128, -128,
    1, 18,   9, 18,
};

// ---------- diameter sign U+2300 (⌀) ----------
//
// A capital-O sized circle with a diagonal slash from upper-right to
// lower-left (Norwegian / engineering convention). Approximated by
// an 8-segment octagon spanning x∈[1,17], y∈[1,22]. The slash sits
// just inside the octagon's outer bounds so it never reaches outside
// the line's vertical advance even when neighbour glyphs hug.
inline constexpr std::int8_t k_diameter_strokes[] = {
     9,  1,  15,  3,   17, 11,  15, 19,
     9, 22,   3, 19,    1, 11,   3,  3,
     9,  1,
    -128, -128,
    15,  1,   3, 22,
};

// ---------- lookup table ----------

struct ExtendedGlyph {
    char32_t      codepoint;
    std::int8_t   advance;          // raw Hershey `o` (pre-`k_advance_factor`)
    std::int8_t   min_x;            // visible left bearing
    std::int8_t   max_x;            // visible right bearing
    std::int8_t const* strokes_data;
    std::uint16_t strokes_count;
};

inline constexpr ExtendedGlyph k_extended_glyphs[] = {
    // U+00B0 °  — advance leaves a small gutter past max_x=7.
    { 0x00B0, /*adv*/ 9, /*min*/ 1, /*max*/ 7,
      k_degree_strokes, sizeof(k_degree_strokes) / sizeof(std::int8_t) },
    // U+00B1 ±  — wider, matches digit advance.
    { 0x00B1, /*adv*/ 11, /*min*/ 1, /*max*/ 9,
      k_plusminus_strokes, sizeof(k_plusminus_strokes) / sizeof(std::int8_t) },
    // U+2300 ⌀  — capital-O kerning so it sits naturally inline with
    //              cap-height letters.
    { 0x2300, /*adv*/ 18, /*min*/ 1, /*max*/ 17,
      k_diameter_strokes, sizeof(k_diameter_strokes) / sizeof(std::int8_t) },
};

inline ExtendedGlyph const* lookup_extended(char32_t cp) noexcept {
    for (auto const& g : k_extended_glyphs) {
        if (g.codepoint == cp) return &g;
    }
    return nullptr;
}

} // namespace cadpp::hershey::detail
